"""
DriftGuard Drift Auditor Agent.
Evaluates cross-artifact candidate pairs using Tree-sitter AST nodes,
Sourcegraph SCIP symbol consumers, OmniRoute dynamic model gateway,
and the Verbatim Anti-Hallucination Verification Invariant.
"""

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import httpx

from app import config
from app.agents.delta_scanner import GitDeltaReport
from app.analysis.evidence_verifier import EvidenceVerifier
from app.analysis.output_validator import DriftPrediction, validate_output
from app.analysis.prompts import build_baseline_prompt
from app.intelligence.scip_indexer import SCIPIndexer
from app.intelligence.treesitter_parser import TreeSitterEngine

logger = logging.getLogger(__name__)


@dataclass
class ConfirmedDrift:
    """Represents an evidence-grounded, verified cross-artifact contradiction."""
    drift_id: str
    category: str
    artifact_1_path: str
    artifact_2_path: str
    evidence_1: str
    evidence_2: str
    line_1: str = ""
    line_2: str = ""
    rationale: str = ""
    suggested_fix: str = ""
    severity: str = "medium"
    gateway_provider: str = ""

    def to_dict(self) -> dict:
        return {
            "drift_id": self.drift_id,
            "category": self.category,
            "artifact_1": self.artifact_1_path,
            "artifact_2": self.artifact_2_path,
            "evidence_1": self.evidence_1,
            "evidence_2": self.evidence_2,
            "line_1": self.line_1,
            "line_2": self.line_2,
            "rationale": self.rationale,
            "suggested_fix": self.suggested_fix,
            "severity": self.severity,
            "gateway_provider": self.gateway_provider,
        }


@dataclass
class DriftAuditReport:
    """Complete report generated by the Drift Auditor Agent."""
    total_candidates: int = 0
    confirmed_drifts: List[ConfirmedDrift] = field(default_factory=list)
    rejected_hallucinations: int = 0
    consistent_pairs: int = 0
    gateway_model_used: str = ""

    def to_dict(self) -> dict:
        return {
            "total_candidates": self.total_candidates,
            "confirmed_count": len(self.confirmed_drifts),
            "rejected_hallucinations": self.rejected_hallucinations,
            "consistent_pairs": self.consistent_pairs,
            "gateway_model": self.gateway_model_used,
            "drifts": [d.to_dict() for d in self.confirmed_drifts],
        }


class DriftAuditorAgent:
    """
    Autonomous Auditor Agent.
    Bridges incremental git perception with multi-language code intelligence
    and LLM contradiction analysis via OmniRoute.
    """

    def __init__(
        self,
        workspace_path: Path,
        treesitter_engine: Optional[TreeSitterEngine] = None,
        scip_indexer: Optional[SCIPIndexer] = None,
        omniroute_host: Optional[str] = None,
        omniroute_api_key: Optional[str] = None,
    ):
        self.workspace_path = Path(workspace_path).resolve()
        self.ts = treesitter_engine or TreeSitterEngine()
        self.scip = scip_indexer or SCIPIndexer(workspace_path=self.workspace_path, treesitter_engine=self.ts)
        self.verifier = EvidenceVerifier()
        self.omniroute_host = omniroute_host or config.OMNIROUTE_HOST
        self.omniroute_api_key = omniroute_api_key or config.OMNIROUTE_API_KEY or os.getenv("OMNIROUTE_API_KEY", "")

    def generate_candidate_pairs(self, delta_report: GitDeltaReport) -> List[Dict[str, Any]]:
        """
        Discovers candidate artifact pairs for delta files by querying Tree-sitter ASTs
        and the SCIP cross-file symbol graph.
        """
        candidates: List[Dict[str, Any]] = []
        changed_rel_paths = [f.path for f in delta_report.files]
        impact_map = self.scip.get_cross_file_impact(changed_rel_paths)

        # 0. Pre-filter candidate test files once, skipping heavy non-source directories
        ignored_dirs = {".git", ".venv", "venv", "node_modules", "vendor", "__pycache__", "graphify-out", ".gemini"}
        test_files: List[Path] = []
        try:
            for p in self.workspace_path.rglob("*"):
                if any(part in ignored_dirs or part.startswith(".") for part in p.parts):
                    continue
                if p.is_file() and ("test" in p.name.lower() or "spec" in p.name.lower()):
                    test_files.append(p)
        except Exception as e:
            logger.debug(f"Failed scanning test files: {e}")

        # Build candidate pairs from changed files and their SCIP consumers
        for changed_file in delta_report.files:
            file_path = self.workspace_path / changed_file.path
            if not file_path.exists():
                continue

            # 1. Parse AST of changed file and find symbols on modified lines
            affected_symbols = []
            if self.ts.supports_file(file_path):
                parsed = self.ts.parse_file(file_path)
                affected_symbols = parsed.get_symbols_in_lines(set(changed_file.modified_lines))

            # 2. Check consumers discovered via SCIP references
            consumers = impact_map.get(changed_file.path, set())
            for consumer_path in consumers:
                candidates.append({
                    "artifact_1": {"path": changed_file.path, "type": "source_code"},
                    "artifact_2": {"path": consumer_path, "type": "consumer_code"},
                    "relationship_type": "symbol_reference",
                    "affected_symbols": [s.name for s in affected_symbols],
                })

            # 3. Pair source code with candidate unit tests from pre-filtered list
            stem = file_path.stem.lower()
            for cand_path in test_files:
                cand_rel = str(cand_path.relative_to(self.workspace_path))
                cand_name = cand_path.stem.lower()
                if (stem in cand_name or cand_name.replace("test_", "") == stem) and cand_rel != changed_file.path:
                    candidates.append({
                        "artifact_1": {"path": changed_file.path, "type": "source_code"},
                        "artifact_2": {"path": cand_rel, "type": "test"},
                        "relationship_type": "test_vs_code",
                        "affected_symbols": [s.name for s in affected_symbols],
                    })

            # 4. Pair source code with dependency manifests if new imports detected
            if self.ts.supports_file(file_path):
                parsed = self.ts.parse_file(file_path)
                if parsed.imports:
                    for manifest_name in ("package.json", "pyproject.toml", "Cargo.toml", "go.mod"):
                        manifest_file = self.workspace_path / manifest_name
                        if manifest_file.exists():
                            candidates.append({
                                "artifact_1": {"path": changed_file.path, "type": "source_code"},
                                "artifact_2": {"path": manifest_name, "type": "dependency"},
                                "relationship_type": "dependency_vs_code",
                                "affected_symbols": parsed.imports[:5],
                            })

        # Deduplicate candidate pairs
        unique_candidates = []
        seen = set()
        for c in candidates:
            pair_key = tuple(sorted([c["artifact_1"]["path"], c["artifact_2"]["path"]]))
            if pair_key not in seen:
                seen.add(pair_key)
                unique_candidates.append(c)

        return unique_candidates

    def audit_candidate(
        self,
        candidate: Dict[str, Any],
        model: Optional[str] = None,
    ) -> Optional[ConfirmedDrift]:
        """
        Audits a single candidate pair via OmniRoute and enforces verbatim verification.
        """
        a1_path = candidate["artifact_1"]["path"]
        a2_path = candidate["artifact_2"]["path"]
        rel_type = candidate.get("relationship_type", "cross_artifact")

        file1 = self.workspace_path / a1_path
        file2 = self.workspace_path / a2_path

        if not file1.exists() or not file2.exists():
            return None

        content1 = file1.read_text(encoding="utf-8", errors="replace")[:config.MAX_CONTEXT_CHARS]
        content2 = file2.read_text(encoding="utf-8", errors="replace")[:config.MAX_CONTEXT_CHARS]

        # 1. Build Grounded Prompt
        prompt = build_baseline_prompt(
            artifact_1_path=a1_path,
            artifact_1_type=candidate["artifact_1"].get("type", "source_code"),
            artifact_1_content=content1,
            artifact_2_path=a2_path,
            artifact_2_type=candidate["artifact_2"].get("type", "consumer_code"),
            artifact_2_content=content2,
        )

        # 2. Invoke OmniRoute Model Gateway
        target_model = model or config.DEFAULT_MODEL
        pred, gateway_used = self._call_omniroute_gateway(prompt, target_model)

        if not pred or not pred.drift_present:
            return None

        # 3. Enforce Mathematical Verbatim Verification Invariant:
        # F1 \sqsubseteq C1 and F2 \sqsubseteq C2
        verif_result = self.verifier.verify(pred, content1, content2)

        if verif_result.status == "Confirmed Drift":
            import uuid
            return ConfirmedDrift(
                drift_id=f"drift-{uuid.uuid4().hex[:6]}",
                category=pred.drift_type or rel_type,
                artifact_1_path=a1_path,
                artifact_2_path=a2_path,
                evidence_1=pred.extracted_fact_1,
                evidence_2=pred.extracted_fact_2,
                line_1=pred.artifact_1_lines,
                line_2=pred.artifact_2_lines,
                rationale=pred.evidence or verif_result.details,
                suggested_fix=pred.expected_fix,
                severity=pred.severity or "medium",
                gateway_provider=gateway_used,
            )

        logger.debug(f"Discarded unverified/hallucinated drift for {a1_path} <-> {a2_path}: {verif_result.details}")
        return None

    def _call_omniroute_gateway(self, prompt: str, model_name: str) -> tuple[Optional[DriftPrediction], str]:
        """
        Calls OmniRoute local gateway via OpenAI-compatible endpoint.
        Falls back to local Ollama if OmniRoute is offline.
        """
        headers = {"Content-Type": "application/json"}
        if self.omniroute_api_key:
            headers["Authorization"] = f"Bearer {self.omniroute_api_key}"

        payload = {
            "model": model_name,
            "messages": [
                {"role": "system", "content": "You are DriftGuard Auditor. Output strictly valid JSON."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.0,
        }

        # 1. Try OmniRoute Gateway
        endpoint = f"{self.omniroute_host.rstrip('/')}/chat/completions"
        try:
            with httpx.Client(timeout=90.0) as client:
                res = client.post(endpoint, json=payload, headers=headers)
                if res.status_code == 200:
                    data = res.json()
                    content = data["choices"][0]["message"]["content"]
                    parsed = validate_output(content)
                    if parsed.success and parsed.prediction:
                        return parsed.prediction, f"omniroute/{model_name}"
        except Exception as e:
            logger.debug(f"OmniRoute request to {endpoint} failed: {e}. Checking fallback.")

        # 2. Try Fallback Ollama Client
        try:
            from app.analysis.llm_client import LLMClient
            llm = LLMClient(model=config.OLLAMA_MODEL)
            parsed = llm.generate(prompt)
            if parsed.success and parsed.prediction:
                return parsed.prediction, f"ollama/{config.OLLAMA_MODEL}"
        except Exception as e:
            logger.debug(f"Ollama fallback failed: {e}")

        return None, "none"

    def audit_delta(
        self,
        delta_report: GitDeltaReport,
        max_candidates: Optional[int] = None,
        model: Optional[str] = None,
    ) -> DriftAuditReport:
        """
        Executes end-to-end drift auditing on all candidates generated from a git delta.
        """
        candidates = self.generate_candidate_pairs(delta_report)
        if max_candidates:
            candidates = candidates[:max_candidates]

        report = DriftAuditReport(
            total_candidates=len(candidates),
            gateway_model_used=model or config.DEFAULT_MODEL,
        )

        for cand in candidates:
            drift = self.audit_candidate(cand, model=model)
            if drift:
                report.confirmed_drifts.append(drift)
            else:
                report.consistent_pairs += 1

        return report
